runtime: python27
api_version: 1
threadsafe: true

runtime_config:
  python_version: 3

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.app

env_variables:
  CLOUD_SQL_USERNAME: geccles
  CLOUD_SQL_PASSWORD: holly96
  CLOUD_SQL_DATABASE_NAME: customers
  CLOUD_SQL_CONNECTION_NAME: menuqr-ie:europe-west2:menuqr-instance